### ISSUE TITLE
Invalid execution chain ID

### ISSUE THREAD

**Issue by piavgh** [flashbots/builder-playground#13]
I'm not sure where to ask this kind of question, so I create an issue. Please kindly tell me where to move it if needed.

I'm using builder-playground and I sometimes get this warning: 

```
Invalid execution chain ID. Please switch to correct chain ID on endpoint, received: Custom(1337), expected: Mainnet, endpoint: http://localhost:8551/, auth=true, service: deposit_contract_rpc
```

What is the problem here? I tried to search for the 1337 config but can't find it anywhere in the code (from what I know, 1337 is for a custom development network)

**Comment by ferranbt** [comment]
Hey! Yes, I saw the warning too. Will try to fix it.
